---
- name: Check driver installation status
  shell: modinfo ena | grep -i "^version:" | grep -Po "(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)"
  register: ena_driver_version
  changed_when: ena_driver_version.stdout != aws_ena_driver_version
  ignore_errors: True

- name: Install ENA driver
  import_tasks: install.yml
  when: ena_driver_version.stdout is defined and (ena_driver_version.stdout != aws_ena_driver_version)
